//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailTran
    {
        public string TransactionID { get; set; }
        public string ProductID { get; set; }
        public int Quantity { get; set; }
    
        public virtual MsProducts MsProduct { get; set; }
        public virtual HeaderTran HeaderTran { get; set; }
    }
}
